name: Hello World

on:
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello...
        run: echo "Hello"
        
  world:
    runs-on: ubuntu-latest
    steps:  
      - name: ...World
        run: echo "World"
        
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: List things
        run: ls -la
        
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Rainbow Exists
        run: test -f ./rainbow-fruit.md
  
       
        
